const ICON={
 book:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 5C4 4 5 3.5 6 3.5H12V20.5H6C5 20.5 4 20 4 19V5Z" stroke="currentColor" stroke-width="1.8"/><path d="M20 5C20 4 19 3.5 18 3.5H12V20.5H18C19 20.5 20 20 20 19V5Z" stroke="currentColor" stroke-width="1.8"/></svg>',
 refresh:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 12C4 7.6 7.6 4 12 4C14.5 4 16.7 5.2 18.1 7" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><path d="M20 12C20 16.4 16.4 20 12 20C9.5 20 7.3 18.8 5.9 17" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><path d="M18 4V7.5H14.5M6 20V16.5H9.5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>',
 home:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 11L12 4L20 11V19C20 19.6 19.6 20 19 20H14V14H10V20H5C4.4 20 4 19.6 4 19V11Z" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg>',
 chev:'<svg viewBox="0 0 24 24" fill="none"><path d="M9 6L15 12L9 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
 card:'<svg viewBox="0 0 24 24" fill="none"><rect x="3" y="6" width="14" height="10" rx="2" stroke="currentColor" stroke-width="1.8"/><path d="M7 3H21V13" stroke="currentColor" stroke-width="1.8"/></svg>',
 key:'<svg viewBox="0 0 24 24" fill="none"><circle cx="8" cy="14" r="4" stroke="currentColor" stroke-width="1.8"/><path d="M11 11L20 2M17 5L19 7M14 8L16 10" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',
 clock:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.8"/><path d="M12 7V12L15.5 14" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',
 chart:'<svg viewBox="0 0 24 24" fill="none"><path d="M4 20V4M4 20H20" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><rect x="7" y="12" width="3" height="6" fill="currentColor"/><rect x="12" y="8" width="3" height="10" fill="currentColor"/><rect x="17" y="14" width="3" height="4" fill="currentColor"/></svg>',
 globe:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.8"/><path d="M3 12H21M12 3C14.5 6 14.5 18 12 21M12 3C9.5 6 9.5 18 12 21" stroke="currentColor" stroke-width="1.6"/></svg>',
 target:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="8" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="12" r="3" stroke="currentColor" stroke-width="1.8"/><path d="M12 2V5M12 19V22M2 12H5M19 12H22" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',
 check:'<svg viewBox="0 0 24 24" fill="none"><path d="M5 12.5L10 17L19 7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
};

function svgClimateVsWeather(){return `<div class="diagram"><svg viewBox="0 0 760 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Comparação entre tempo atmosférico e clima"><rect x="18" y="18" width="724" height="214" rx="16" fill="#F8F7F1"/><line x1="380" y1="38" x2="380" y2="212" stroke="#D7DCE4" stroke-width="2"/>
<text x="48" y="52" font-family="Arial" font-size="19" font-weight="700" fill="#3F5F9C">TEMPO</text><text x="48" y="77" font-family="Arial" font-size="14" fill="#374151">O que a atmosfera está fazendo</text><text x="48" y="101" font-family="Arial" font-size="13" fill="#5B6472">Agora, hoje, nesta hora, neste lugar.</text>
<circle cx="83" cy="150" r="28" fill="#EAF0FF"/><path d="M70 151h27a10 10 0 0 0-19-4 8 8 0 0 0-8 4z" fill="#5E87E8"/><text x="47" y="192" font-family="Arial" font-size="12" fill="#374151">chuva · vento · temperatura</text>
<text x="410" y="52" font-family="Arial" font-size="19" font-weight="700" fill="#3F5F9C">CLIMA</text><text x="410" y="77" font-family="Arial" font-size="14" fill="#374151">O padrão que aparece ao longo do tempo</text><text x="410" y="101" font-family="Arial" font-size="13" fill="#5B6472">Muitos anos de observações e estatística.</text>
<polyline points="418,170 452,145 486,162 520,130 554,149 588,118 622,136 656,106 690,122" fill="none" stroke="#5E87E8" stroke-width="3"/><line x1="418" y1="180" x2="690" y2="180" stroke="#CBD2DE" stroke-width="2" stroke-dasharray="5 5"/><text x="430" y="203" font-family="Arial" font-size="12" fill="#374151">médias · padrões · variabilidade</text></svg><div class="diagram-cap">O tempo é o estado momentâneo; o clima é o padrão de longo prazo construído a partir de muitos estados do tempo.</div></div>`}
function svgTemperatureAmplitude(){return `<div class="diagram"><svg viewBox="0 0 760 280" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Comparação de amplitude térmica entre litoral e interior"><rect x="18" y="18" width="724" height="244" rx="16" fill="#F8F7F1"/><text x="40" y="50" font-family="Arial" font-size="15" font-weight="700" fill="#374151">Mesmo clima médio, amplitudes diferentes</text>
<line x1="72" y1="218" x2="700" y2="218" stroke="#9AA4B3"/><line x1="72" y1="74" x2="72" y2="218" stroke="#9AA4B3"/>
<path d="M92 170 C145 150 172 156 214 166 S305 182 348 163 S432 141 476 156 S568 180 610 156 S671 132 690 144" fill="none" stroke="#5E87E8" stroke-width="4"/><path d="M92 126 C140 98 174 101 212 128 S299 154 344 117 S430 87 476 122 S563 149 609 110 S667 85 690 103" fill="none" stroke="#B77B19" stroke-width="4"/>
<text x="96" y="248" font-family="Arial" font-size="12" fill="#374151">Litoral</text><text x="620" y="248" font-family="Arial" font-size="12" fill="#374151">Interior</text><rect x="98" y="80" width="12" height="4" fill="#B77B19"/><text x="118" y="84" font-family="Arial" font-size="11" fill="#6D5A2B">maior variação</text><rect x="240" y="80" width="12" height="4" fill="#5E87E8"/><text x="260" y="84" font-family="Arial" font-size="11" fill="#3F5F9C">variação menor</text>
<text x="78" y="69" font-family="Arial" font-size="10" fill="#475569">temperatura</text><text x="645" y="218" font-family="Arial" font-size="10" fill="#475569">tempo</text></svg><div class="diagram-cap">Maritimidade tende a suavizar as variações; continentalidade tende a amplificá-las.</div></div>`}
function svgPressure(){return `<div class="diagram"><svg viewBox="0 0 760 280" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Relação entre temperatura, pressão e movimento do ar"><rect x="18" y="18" width="724" height="244" rx="16" fill="#F8F7F1"/>
<circle cx="200" cy="136" r="66" fill="#E3F3EB"/><text x="200" y="126" text-anchor="middle" font-family="Arial" font-size="18" font-weight="700" fill="#245E44">AR FRIO</text><text x="200" y="148" text-anchor="middle" font-family="Arial" font-size="13" fill="#374151">mais denso</text><path d="M200 72V40" stroke="#23835A" stroke-width="4"/><path d="M188 50L200 38L212 50" fill="none" stroke="#23835A" stroke-width="4"/>
<circle cx="560" cy="136" r="66" fill="#EEF3FF"/><text x="560" y="126" text-anchor="middle" font-family="Arial" font-size="18" font-weight="700" fill="#3F5F9C">AR QUENTE</text><text x="560" y="148" text-anchor="middle" font-family="Arial" font-size="13" fill="#374151">menos denso</text><path d="M560 201V233" stroke="#5E87E8" stroke-width="4"/><path d="M548 223L560 235L572 223" fill="none" stroke="#5E87E8" stroke-width="4"/>
<path d="M270 136H490" stroke="#697384" stroke-width="3" marker-end="url(#pArr)"/><text x="380" y="119" text-anchor="middle" font-family="Arial" font-size="13" fill="#374151">diferença de pressão</text><text x="380" y="160" text-anchor="middle" font-family="Arial" font-size="12" fill="#5B6472">move o ar</text><text x="40" y="48" font-family="Arial" font-size="15" font-weight="700" fill="#374151">Ideia-chave</text><text x="40" y="75" font-family="Arial" font-size="12" fill="#5B6472">A pressão não é só um número: diferenças de pressão ajudam a explicar os ventos.</text><defs><marker id="pArr" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#697384"/></marker></defs></svg><div class="diagram-cap">Em termos simplificados: diferenças de pressão criam o gradiente que impulsiona o movimento do ar.</div></div>`}
function svgAtmosphere(){return `<div class="diagram"><svg viewBox="0 0 760 350" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Camadas da atmosfera"><rect x="18" y="18" width="724" height="314" rx="16" fill="#F8F7F1"/><path d="M82 292 Q380 250 678 292" fill="none" stroke="#7A5A2B" stroke-width="8"/><rect x="90" y="254" width="580" height="38" rx="8" fill="#DDEBF4"/><rect x="90" y="214" width="580" height="40" rx="8" fill="#E8F3DE"/><rect x="90" y="158" width="580" height="56" rx="8" fill="#F9EED9"/><rect x="90" y="98" width="580" height="60" rx="8" fill="#F8E1E1"/><rect x="90" y="58" width="580" height="40" rx="8" fill="#EEE9FA"/>
<text x="112" y="78" font-family="Arial" font-size="14" font-weight="700" fill="#4B3D74">Exosfera</text><text x="112" y="124" font-family="Arial" font-size="14" font-weight="700" fill="#7B3434">Termosfera</text><text x="112" y="190" font-family="Arial" font-size="14" font-weight="700" fill="#72551B">Mesosfera</text><text x="112" y="239" font-family="Arial" font-size="14" font-weight="700" fill="#346D45">Estratosfera</text><text x="112" y="279" font-family="Arial" font-size="14" font-weight="700" fill="#315E78">Troposfera</text>
<text x="540" y="124" font-family="Arial" font-size="11" fill="#5B6472">auroras</text><text x="540" y="190" font-family="Arial" font-size="11" fill="#5B6472">meteoros</text><text x="500" y="239" font-family="Arial" font-size="11" fill="#5B6472">ozônio</text><text x="490" y="279" font-family="Arial" font-size="11" fill="#5B6472">tempo meteorológico</text><text x="42" y="46" font-family="Arial" font-size="15" font-weight="700" fill="#374151">Regra de prova</text><text x="42" y="322" font-family="Arial" font-size="11" fill="#5B6472">Clima e tempo acontecem principalmente na troposfera.</text></svg><div class="diagram-cap">As cinco camadas principais são organizadas pela altitude; a troposfera é a camada diretamente ligada ao tempo meteorológico.</div></div>`}
function svgRadiationAndFactors(){return `<div class="diagram"><svg viewBox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Fatores que alteram o clima"><rect x="18" y="18" width="724" height="264" rx="16" fill="#F8F7F1"/><circle cx="105" cy="105" r="35" fill="#F4D58A"/><g stroke="#B77B19" stroke-width="3"><line x1="105" y1="55" x2="105" y2="34"/><line x1="105" y1="176" x2="105" y2="155"/><line x1="55" y1="105" x2="34" y2="105"/><line x1="176" y1="105" x2="155" y2="105"/></g><text x="105" y="111" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#7A5A20">SOL</text>
<rect x="220" y="62" width="148" height="72" rx="12" fill="#EAF0FF"/><text x="294" y="90" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#3F5F9C">LATITUDE</text><text x="294" y="112" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">ângulo da radiação</text>
<rect x="400" y="62" width="148" height="72" rx="12" fill="#EAF0FF"/><text x="474" y="90" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#3F5F9C">ALTITUDE</text><text x="474" y="112" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">pressão e temperatura</text>
<rect x="580" y="62" width="138" height="72" rx="12" fill="#EAF0FF"/><text x="649" y="90" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#3F5F9C">MAR</text><text x="649" y="112" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">calor e umidade</text>
<rect x="220" y="166" width="148" height="72" rx="12" fill="#EEF7F1"/><text x="294" y="194" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#2B6C4D">ALBEDO</text><text x="294" y="216" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">reflete energia</text>
<rect x="400" y="166" width="148" height="72" rx="12" fill="#EEF7F1"/><text x="474" y="194" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#2B6C4D">CORRENTES</text><text x="474" y="216" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">redistribuem calor</text>
<rect x="580" y="166" width="138" height="72" rx="12" fill="#EEF7F1"/><text x="649" y="194" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#2B6C4D">EFEITO ESTUFA</text><text x="649" y="216" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">radiação infravermelha</text>
<path d="M140 105H210M368 98H392M548 98H572M368 202H392M548 202H572" stroke="#7B8494" stroke-width="2" marker-end="url(#fArr)"/><defs><marker id="fArr" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#475569"/></marker></defs></svg><div class="diagram-cap">Os fatores climáticos não atuam isoladamente; eles alteram como a energia solar é recebida, armazenada e redistribuída.</div></div>`}
function svgCirculation(){return `<div class="diagram"><svg viewBox="0 0 760 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Circulação geral da atmosfera"><rect x="18" y="18" width="724" height="294" rx="16" fill="#F8F7F1"/><line x1="80" y1="248" x2="680" y2="248" stroke="#9AA4B3" stroke-width="2"/><line x1="80" y1="82" x2="680" y2="82" stroke="#9AA4B3" stroke-width="2"/><text x="80" y="68" font-family="Arial" font-size="12" fill="#5B6472">alta latitude norte</text><text x="80" y="273" font-family="Arial" font-size="12" fill="#5B6472">alta latitude sul</text><text x="380" y="72" text-anchor="middle" font-family="Arial" font-size="12" font-weight="700" fill="#374151">Equador</text>
<path d="M110 220 Q180 100 250 220" fill="none" stroke="#5E87E8" stroke-width="5"/><path d="M290 220 Q380 105 470 220" fill="none" stroke="#B77B19" stroke-width="5"/><path d="M510 220 Q590 125 650 220" fill="none" stroke="#23835A" stroke-width="5"/>
<text x="180" y="147" text-anchor="middle" font-family="Arial" font-size="14" font-weight="700" fill="#3F5F9C">Hadley</text><text x="380" y="149" text-anchor="middle" font-family="Arial" font-size="14" font-weight="700" fill="#7A5A20">Ferrel</text><text x="580" y="163" text-anchor="middle" font-family="Arial" font-size="14" font-weight="700" fill="#2B6C4D">Polar</text>
<path d="M345 222V105" stroke="#C64646" stroke-width="4" marker-end="url(#cArr)"/><text x="380" y="112" font-family="Arial" font-size="11" fill="#6E2E2E">ar quente sobe</text><path d="M215 105V217" stroke="#697384" stroke-width="3" marker-end="url(#cArr2)"/><text x="165" y="193" font-family="Arial" font-size="11" fill="#5B6472">ar desce</text><defs><marker id="cArr" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#C64646"/></marker><marker id="cArr2" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#697384"/></marker></defs></svg><div class="diagram-cap">A circulação geral conecta aquecimento desigual, subida e descida do ar, pressão e ventos em escala planetária.</div></div>`}
function svgFronts(){return `<div class="diagram"><svg viewBox="0 0 760 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Comparação entre frente fria e frente quente"><rect x="18" y="18" width="724" height="214" rx="16" fill="#F8F7F1"/><text x="45" y="52" font-family="Arial" font-size="16" font-weight="700" fill="#374151">Frente fria</text><path d="M55 162 Q170 92 310 162" fill="none" stroke="#527FC8" stroke-width="15"/><path d="M104 140 l18 0 l-9 15z M168 125 l18 0 l-9 15z M232 125 l18 0 l-9 15z" fill="#527FC8"/><text x="55" y="193" font-family="Arial" font-size="12" fill="#374151">ar frio avança</text><text x="55" y="210" font-family="Arial" font-size="11" fill="#5B6472">subida mais brusca do ar quente</text>
<text x="410" y="52" font-family="Arial" font-size="16" font-weight="700" fill="#374151">Frente quente</text><path d="M420 162 Q540 92 685 162" fill="none" stroke="#D2774E" stroke-width="15"/><path d="M480 148 a12 12 0 0 0 24 0 M540 132 a12 12 0 0 0 24 0 M600 132 a12 12 0 0 0 24 0" fill="none" stroke="#D2774E" stroke-width="3"/><text x="420" y="193" font-family="Arial" font-size="12" fill="#374151">ar quente avança</text><text x="420" y="210" font-family="Arial" font-size="11" fill="#5B6472">subida mais gradual do ar quente</text></svg><div class="diagram-cap">A geometria da subida do ar ajuda a explicar diferenças na velocidade e no tipo de precipitação associados às frentes.</div></div>`}
function svgENSO(){return `<div class="diagram"><svg viewBox="0 0 760 340" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="El Niño, La Niña e condições normais no Pacífico"><rect x="18" y="18" width="724" height="304" rx="16" fill="#F8F7F1"/><text x="52" y="46" font-family="Arial" font-size="15" font-weight="700" fill="#374151">Pacífico equatorial: o oceano e a atmosfera se acoplam</text>
<line x1="68" y1="116" x2="692" y2="116" stroke="#97A2B3" stroke-width="2"/><line x1="68" y1="246" x2="692" y2="246" stroke="#97A2B3" stroke-width="2"/><text x="76" y="105" font-family="Arial" font-size="11" fill="#5B6472">Ásia</text><text x="645" y="105" font-family="Arial" font-size="11" fill="#5B6472">América do Sul</text>
<path d="M110 148 C220 126 330 128 440 148 S580 180 660 154" fill="none" stroke="#C9D4E4" stroke-width="38" opacity=".8"/><text x="380" y="151" text-anchor="middle" font-family="Arial" font-size="12" fill="#344154">água superficial</text>
<path d="M160 187H640" stroke="#697384" stroke-width="4" marker-end="url(#eArr)"/><text x="392" y="177" text-anchor="middle" font-family="Arial" font-size="11" fill="#5B6472">alísios</text>
<path d="M620 265 C560 216 510 212 468 260" fill="none" stroke="#527FC8" stroke-width="4"/><path d="M640 265 C580 214 520 207 488 264" fill="none" stroke="#527FC8" stroke-width="4"/><text x="607" y="291" font-family="Arial" font-size="11" fill="#3F5F9C">ressurgência</text>
<rect x="80" y="272" width="154" height="28" rx="8" fill="#EEF7F1"/><text x="157" y="290" text-anchor="middle" font-family="Arial" font-size="11" font-weight="700" fill="#2B6C4D">NORMAL: água quente no oeste</text><rect x="300" y="272" width="154" height="28" rx="8" fill="#FFF1E9"/><text x="377" y="290" text-anchor="middle" font-family="Arial" font-size="11" font-weight="700" fill="#8B4A2C">EL NIÑO: quente se desloca</text><rect x="520" y="272" width="160" height="28" rx="8" fill="#EAF0FF"/><text x="600" y="290" text-anchor="middle" font-family="Arial" font-size="11" font-weight="700" fill="#3F5F9C">LA NIÑA: alísios fortes</text><defs><marker id="eArr" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#697384"/></marker></defs></svg><div class="diagram-cap">O ponto central do ENSO não é decorar “quente ou frio”: é entender a ligação entre temperatura do mar, ventos, pressão, convecção e distribuição da chuva.</div></div>`}
function svgTropicalCyclone(){return `<div class="diagram"><svg viewBox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cadeia simplificada de formação de ciclone tropical"><rect x="18" y="18" width="724" height="264" rx="16" fill="#F8F7F1"/><g><rect x="45" y="74" width="126" height="100" rx="12" fill="#FFF1E9"/><text x="108" y="106" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#8B4A2C">oceano quente</text><text x="108" y="129" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">≥ ~26,5°C</text><text x="108" y="151" text-anchor="middle" font-family="Arial" font-size="10.5" fill="#5B6472">energia + evaporação</text></g>
<path d="M176 124H216" stroke="#697384" stroke-width="3" marker-end="url(#tArr)"/><g><rect x="220" y="74" width="126" height="100" rx="12" fill="#EDF6F1"/><text x="283" y="106" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#2B6C4D">convecção</text><text x="283" y="129" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">ar úmido sobe</text><text x="283" y="151" text-anchor="middle" font-family="Arial" font-size="10.5" fill="#5B6472">condensação libera calor</text></g>
<path d="M351 124H391" stroke="#697384" stroke-width="3" marker-end="url(#tArr)"/><g><rect x="395" y="74" width="126" height="100" rx="12" fill="#EAF0FF"/><text x="458" y="106" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#3F5F9C">baixa pressão</text><text x="458" y="129" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">ar converge</text><text x="458" y="151" text-anchor="middle" font-family="Arial" font-size="10.5" fill="#5B6472">circulação se organiza</text></g>
<path d="M526 124H566" stroke="#697384" stroke-width="3" marker-end="url(#tArr)"/><g><rect x="570" y="74" width="145" height="100" rx="12" fill="#F6EDF5"/><text x="642" y="106" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="#6E4B74">ciclone tropical</text><text x="642" y="129" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">Coriolis organiza</text><text x="642" y="151" text-anchor="middle" font-family="Arial" font-size="10.5" fill="#5B6472">desde que as condições sustentem</text></g>
<text x="45" y="218" font-family="Arial" font-size="12" font-weight="700" fill="#374151">Condições adicionais importam:</text><text x="45" y="240" font-family="Arial" font-size="11" fill="#5B6472">umidade na troposfera · pouco cisalhamento vertical · perturbação inicial · distância suficiente do Equador</text><text x="45" y="259" font-family="Arial" font-size="11" fill="#5B6472">Ou seja: água quente é necessária, mas não é a única condição.</text><defs><marker id="tArr" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#697384"/></marker></defs></svg><div class="diagram-cap">A formação de um ciclone tropical é um processo de retroalimentação entre oceano quente, convecção e organização da circulação.</div></div>`}
function svgGreenhouse(){return `<div class="diagram"><svg viewBox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Efeito estufa e mudanças climáticas"><rect x="18" y="18" width="724" height="264" rx="16" fill="#F8F7F1"/><circle cx="106" cy="128" r="38" fill="#F4D58A"/><text x="106" y="133" text-anchor="middle" font-family="Arial" font-size="12" font-weight="700" fill="#7A5A20">SOL</text><path d="M149 128H237" stroke="#B77B19" stroke-width="5" marker-end="url(#gArr)"/><text x="190" y="112" text-anchor="middle" font-family="Arial" font-size="11" fill="#5B6472">radiação</text>
<rect x="250" y="75" width="250" height="110" rx="14" fill="#EAF0FF"/><text x="375" y="104" text-anchor="middle" font-family="Arial" font-size="14" font-weight="700" fill="#3F5F9C">superfície + atmosfera</text><text x="375" y="126" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">absorvem energia</text><path d="M375 185V230" stroke="#C64646" stroke-width="5" marker-end="url(#gArr2)"/><text x="412" y="212" font-family="Arial" font-size="11" fill="#6E2E2E">infravermelho</text>
<rect x="525" y="70" width="184" height="120" rx="14" fill="#EEF7F1"/><text x="617" y="99" text-anchor="middle" font-family="Arial" font-size="14" font-weight="700" fill="#2B6C4D">GEE</text><text x="617" y="121" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">absorvem parte</text><text x="617" y="139" text-anchor="middle" font-family="Arial" font-size="11" fill="#374151">da radiação infravermelha</text><path d="M570 185Q520 215 470 185" fill="none" stroke="#2B6C4D" stroke-width="4" marker-end="url(#gArr3)"/><text x="618" y="169" text-anchor="middle" font-family="Arial" font-size="10.5" fill="#5B6472">parte retorna</text>
<rect x="60" y="214" width="260" height="42" rx="10" fill="#FAF0DA"/><text x="190" y="232" text-anchor="middle" font-family="Arial" font-size="11" font-weight="700" fill="#7A5A20">efeito estufa natural</text><text x="190" y="248" text-anchor="middle" font-family="Arial" font-size="10.5" fill="#5B6472">é parte do equilíbrio térmico da Terra</text><rect x="350" y="238" width="340" height="18" rx="9" fill="#F8E4E4"/><text x="520" y="251" text-anchor="middle" font-family="Arial" font-size="10.5" font-weight="700" fill="#762D2D">maior concentração de GEE → maior retenção de energia</text><defs><marker id="gArr" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#B77B19"/></marker><marker id="gArr2" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#C64646"/></marker><marker id="gArr3" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#2B6C4D"/></marker></defs></svg><div class="diagram-cap">A distinção essencial: o efeito estufa natural é necessário; o problema atual é o aumento antrópico da concentração de gases de efeito estufa.</div></div>`}
function svgClimateChangeChain(){return `<div class="diagram"><svg viewBox="0 0 760 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cadeia de mudanças climáticas"><rect x="18" y="18" width="724" height="214" rx="16" fill="#F8F7F1"/><g><rect x="42" y="82" width="122" height="84" rx="12" fill="#FFF1E9"/><text x="103" y="111" text-anchor="middle" font-family="Arial" font-size="12" font-weight="700" fill="#8B4A2C">atividades humanas</text><text x="103" y="133" text-anchor="middle" font-family="Arial" font-size="10.5" fill="#5B6472">fósseis · uso da terra</text></g><path d="M166 124H208" stroke="#697384" stroke-width="3" marker-end="url(#ccArr)"/><g><rect x="212" y="82" width="122" height="84" rx="12" fill="#F8E4E4"/><text x="273" y="111" text-anchor="middle" font-family="Arial" font-size="12" font-weight="700" fill="#762D2D">mais GEE</text><text x="273" y="133" text-anchor="middle" font-family="Arial" font-size="10.5" fill="#5B6472">CO₂ · CH₄ · N₂O</text></g><path d="M336 124H378" stroke="#697384" stroke-width="3" marker-end="url(#ccArr)"/><g><rect x="382" y="82" width="122" height="84" rx="12" fill="#EEF3FF"/><text x="443" y="111" text-anchor="middle" font-family="Arial" font-size="12" font-weight="700" fill="#3F5F9C">mais energia</text><text x="443" y="133" text-anchor="middle" font-family="Arial" font-size="10.5" fill="#5B6472">sistema aquece</text></g><path d="M506 124H548" stroke="#697384" stroke-width="3" marker-end="url(#ccArr)"/><g><rect x="552" y="82" width="166" height="84" rx="12" fill="#EEF7F1"/><text x="635" y="111" text-anchor="middle" font-family="Arial" font-size="12" font-weight="700" fill="#2B6C4D">mudanças climáticas</text><text x="635" y="133" text-anchor="middle" font-family="Arial" font-size="10.5" fill="#5B6472">riscos e impactos</text></g><text x="42" y="57" font-family="Arial" font-size="14" font-weight="700" fill="#374151">O raciocínio que conecta causas e consequências</text><defs><marker id="ccArr" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#697384"/></marker></defs></svg><div class="diagram-cap">Não confunda correlação vaga com mecanismo: a cadeia causal ajuda a explicar por que aumentar gases de efeito estufa altera o balanço de energia.</div></div>`}

const SUBJECTS=[{
 id:"climatologia",name:"Climatologia",tag:"Geografia · Capítulo 3",icon:ICON.globe,
 learningGoal:"Entender como energia, atmosfera e circulação produzem diferentes climas.",
 topics:[
  {id:"clima-tempo",title:"Clima × Tempo",sub:"Comece distinguindo evento momentâneo de padrão de longo prazo",html:`
    ${svgClimateVsWeather()}
    <div class="idea-box"><div class="k">Ideia central</div><p><strong>Tempo</strong> descreve o estado da atmosfera em determinado momento e lugar. <strong>Clima</strong> descreve padrões estatísticos do tempo observados ao longo de períodos longos. Um episódio de chuva é tempo; a recorrência de chuva em uma região faz parte do clima.</p></div>
    <p>Essa distinção evita um erro muito comum: usar um dia frio, uma onda de calor ou uma chuva intensa isolada como se, sozinhos, definissem a mudança do clima. O clima não apaga a variabilidade; ele procura padrões dentro dela.</p>
    <h4>Como os dois se conectam</h4>
    <div class="cause-chain"><div class="cause-step"><strong>1. O tempo acontece</strong><span>Temperatura, pressão, umidade, vento e precipitação variam diariamente.</span></div><div class="cause-link">↓</div><div class="cause-step"><strong>2. Muitos tempos são observados</strong><span>Décadas de medições permitem comparar médias, extremos e frequência de eventos.</span></div><div class="cause-link">↓</div><div class="cause-step"><strong>3. Surge uma descrição climática</strong><span>O clima resume padrões e variabilidade, não uma previsão para um dia específico.</span></div></div>
    <div class="why-box"><div class="k">Por que isso importa?</div><p>Previsão do tempo responde “o que pode acontecer nos próximos dias?”. Climatologia responde “quais padrões e faixas de variação são típicos deste lugar ao longo de muitos anos?”. As duas áreas usam observações atmosféricas, mas fazem perguntas diferentes.</p></div>
    <div class="connection-box"><div class="k">Conexão com os próximos módulos</div><p>Os <strong>elementos do clima</strong> são as variáveis que medimos. Os <strong>fatores climáticos</strong> ajudam a explicar por que essas variáveis diferem de lugar para lugar. A <strong>dinâmica atmosférica</strong> explica como o sistema se movimenta.</p></div>
  `,quiz:[
   {type:"mc",q:"Uma estação registra 34 °C e chuva intensa em uma tarde. Qual conclusão é mais defensável?",options:["O clima da cidade é definido por essa tarde","Isso descreve o tempo; para caracterizar o clima é preciso analisar séries e padrões","A chuva prova uma mudança climática","A temperatura deixa de ser uma variável climática"],correct:1,explain:"A observação é pontual. Clima é caracterizado por padrões e variabilidade em escalas de tempo longas."},
   {type:"mc",q:"Duas décadas mostram aumento persistente da temperatura média de uma região. O que diferencia essa evidência de um dia excepcionalmente quente?",options:["A análise considera uma série temporal e compara a tendência com a variabilidade esperada","Um dia quente não pode ser medido","A média anual elimina todos os extremos","Temperatura diária não pertence ao tempo"],correct:0,explain:"Uma tendência climática é avaliada em séries temporais, levando em conta variabilidade e distribuição dos dados."},
   {type:"mc",challenge:true,q:"Uma cidade teve três anos seguidos acima da média histórica. Qual análise seria mais adequada antes de afirmar uma mudança permanente?",options:["Comparar os dados apenas com o último ano","Examinar uma série mais longa, a variabilidade e outros indicadores climáticos","Descartar os anos porque extremos não contam","Usar somente a maior temperatura registrada"],correct:1,explain:"Períodos curtos podem conter variabilidade natural. A avaliação climática precisa de contexto temporal e estatístico."},
   {type:"open",q:"Explique, em poucas frases, por que previsão do tempo e climatologia respondem perguntas diferentes.",model:"A previsão do tempo busca estimar o estado atmosférico em uma escala curta. A climatologia analisa padrões, médias, variabilidade e extremos ao longo de períodos longos.",terms:["tempo","clima","escala temporal"]},
   {type:"mc",q:"Qual situação depende mais claramente de uma descrição climática do que de uma observação do tempo?",options:["A máxima temperatura prevista para amanhã","A frequência típica de chuvas no verão de uma região","A chuva registrada às 16h de hoje","A direção do vento nesta manhã"],correct:1,explain:"A frequência típica ao longo das estações é um padrão de longo prazo, portanto pertence à descrição climática."}
  ]},
  {id:"elementos",title:"Elementos do Clima",sub:"Aprenda a ler um clima como um conjunto de variáveis",html:`
    <div class="concept-grid"><div class="concept"><div class="t">Temperatura</div><div class="d">Indica o estado térmico do ar.</div></div><div class="concept"><div class="t">Umidade</div><div class="d">Mostra a presença de vapor d’água na atmosfera.</div></div><div class="concept"><div class="t">Precipitação</div><div class="d">Água que chega à superfície em forma líquida ou sólida.</div></div><div class="concept"><div class="t">Pressão</div><div class="d">Relaciona-se ao peso do ar e às diferenças que ajudam a gerar ventos.</div></div></div>
    <h4>Temperatura não é apenas uma média</h4><p>A <strong>amplitude térmica</strong> é a diferença entre valores de temperatura, como máxima e mínima de um período. Dois locais podem ter médias parecidas e, ainda assim, comportamentos muito diferentes ao longo do dia ou do ano.</p>${svgTemperatureAmplitude()}
    <h4>Umidade relativa: o contexto importa</h4><p>Umidade relativa é uma medida percentual da quantidade de vapor presente em relação ao máximo que o ar consegue conter naquela temperatura. Como a capacidade de retenção depende da temperatura, a mesma quantidade de vapor pode corresponder a um percentual diferente em momentos diferentes.</p>
    <h4>Precipitação: pense no mecanismo</h4><ul><li><strong>Frontal:</strong> associada à interação entre massas de ar de características diferentes.</li><li><strong>Orográfica:</strong> o relevo força o ar úmido a subir.</li><li><strong>Convectiva:</strong> o aquecimento favorece a subida do ar, formando nuvens convectivas.</li></ul>
    <h4>Pressão e vento</h4>${svgPressure()}<p>Em uma explicação simplificada, o vento está ligado às diferenças de pressão: o ar tende a se mover de regiões de maior pressão para regiões de menor pressão. A rotação da Terra e o relevo também interferem na direção real do escoamento.</p>
    <div class="connection-box"><div class="k">Conexão</div><p>Quando você junta temperatura + umidade + pressão + movimento do ar, começa a sair da lista de definições e a enxergar <strong>mecanismos atmosféricos</strong>.</p></div>
  `,quiz:[
   {type:"mc",q:"Duas cidades têm a mesma temperatura média anual, mas uma possui verões e invernos muito mais contrastantes. Qual medida ajuda diretamente a perceber essa diferença?",options:["Amplitude térmica","Pressão atmosférica média","Latitude absoluta","Precipitação anual isolada"],correct:0,explain:"A amplitude térmica evidencia a diferença entre valores de temperatura em um período e pode revelar contrastes que a média esconde."},
   {type:"mc",q:"Por que 70% de umidade relativa não representa necessariamente a mesma quantidade de vapor d’água em duas situações?",options:["Porque a umidade relativa não depende da temperatura","Porque a capacidade de o ar conter vapor varia com a temperatura","Porque 70% mede apenas precipitação","Porque vapor d’água só existe acima de 70%"],correct:1,explain:"A umidade relativa compara o vapor presente com a capacidade máxima do ar naquela temperatura."},
   {type:"mc",q:"Depois que ar úmido sobe ao encontrar uma serra, ocorre resfriamento e formação de nuvens. Que mecanismo de precipitação está mais diretamente envolvido?",options:["Convectivo","Orográfico","Frontal","Ciclônico exclusivamente"],correct:1,explain:"Na chuva orográfica, o relevo força a ascensão do ar, favorecendo resfriamento, condensação e precipitação."},
   {type:"open",q:"Compare chuva frontal, orográfica e convectiva pelo processo que força o ar a subir.",model:"Na frontal, a ascensão ocorre pela interação entre massas de ar de características diferentes. Na orográfica, o relevo força a subida. Na convectiva, o aquecimento da superfície gera ar mais quente e ascendente.",terms:["frontal","orográfica","convectiva"]},
   {type:"mc",challenge:true,q:"Em uma tarde muito quente, a umidade relativa cai sem grande retirada de vapor d’água. Qual explicação é mais coerente?",options:["O ar ficou mais frio e passou a comportar menos vapor","O aquecimento aumentou a capacidade máxima de vapor do ar, alterando a razão usada na umidade relativa","A pressão atmosférica transforma vapor em chuva imediatamente","A umidade relativa mede diretamente a quantidade absoluta de chuva"],correct:1,explain:"Como a capacidade de retenção de vapor aumenta com a temperatura, a mesma quantidade de vapor pode corresponder a uma umidade relativa menor."}
  ]},
  {id:"atmosfera",title:"Camadas da Atmosfera",sub:"Localize os processos antes de tentar explicá-los",html:`
    ${svgAtmosphere()}
    <p>A atmosfera não é uniforme. Suas propriedades mudam com a altitude, e por isso costuma ser dividida em <strong>troposfera, estratosfera, mesosfera, termosfera e exosfera</strong>.</p>
    <ul><li><strong>Troposfera:</strong> é a camada mais próxima da superfície e a principal região dos fenômenos meteorológicos.</li><li><strong>Estratosfera:</strong> concentra a maior parte do ozônio atmosférico, importante na absorção de radiação ultravioleta.</li><li><strong>Mesosfera:</strong> é uma região em que muitos meteoroides queimam por atrito.</li><li><strong>Termosfera:</strong> recebe forte influência da energia solar e está associada a fenômenos como auroras.</li><li><strong>Exosfera:</strong> é extremamente rarefeita e faz uma transição gradual para o espaço.</li></ul>
    <div class="warning-box"><div class="k">Cuidado com uma simplificação</div><p>As camadas não são “caixas totalmente separadas”. Os limites são regiões de transição, e fenômenos como a ionosfera atravessam partes de mais de uma camada.</p></div>
    <h4>Composição não é o mesmo que camadas</h4><p>As cinco camadas são classificadas principalmente pela estrutura vertical da atmosfera. Já a composição básica do ar perto da superfície é dominada por nitrogênio e oxigênio, além de pequenas quantidades de outros gases e vapor d’água.</p>
    <div class="why-box"><div class="k">Por que isso ajuda na climatologia?</div><p>Porque evita procurar mecanismos climáticos na parte errada da atmosfera. O tempo meteorológico que sentimos na superfície está fortemente ligado à troposfera, onde existe a maior parte da massa de ar e do vapor d’água atmosférico.</p></div>
  `,quiz:[
   {type:"mc",q:"Em qual camada ocorrem a maior parte das nuvens, chuvas e outros fenômenos meteorológicos próximos à superfície?",options:["Estratosfera","Troposfera","Mesosfera","Exosfera"],correct:1,explain:"A troposfera é a camada inferior e concentra a maior parte da massa atmosférica e do vapor d’água relevante ao tempo meteorológico."},
   {type:"mc",q:"Qual associação está correta?",options:["Troposfera - maior parte do tempo meteorológico","Exosfera - principal concentração de vapor d’água","Mesosfera - camada onde vivemos","Estratosfera - camada mais próxima da superfície"],correct:0,explain:"A troposfera é a camada diretamente ligada aos fenômenos meteorológicos cotidianos."},
   {type:"mc",q:"Qual sequência apresenta as camadas principais da atmosfera a partir da superfície?",options:["Troposfera, estratosfera, mesosfera, termosfera, exosfera","Estratosfera, troposfera, termosfera, mesosfera, exosfera","Troposfera, mesosfera, estratosfera, exosfera, termosfera","Exosfera, termosfera, mesosfera, estratosfera, troposfera"],correct:0,explain:"A ordem convencional é troposfera, estratosfera, mesosfera, termosfera e exosfera."},
   {type:"mc",challenge:true,q:"Por que conhecer a estrutura vertical da atmosfera ajuda na climatologia?",options:["Porque todas as camadas têm exatamente o mesmo comportamento","Porque permite relacionar processos e propriedades à altitude em vez de tratar a atmosfera como uma camada uniforme","Porque apenas a exosfera influencia o clima","Porque a altitude não altera os processos atmosféricos"],correct:1,explain:"Temperatura, composição e processos variam com a altitude; distinguir as camadas evita generalizações incorretas."},
   {type:"open",q:"Explique a importância da troposfera para o estudo do tempo e diferencie sua posição da estratosfera.",model:"A troposfera é a camada inferior, onde se concentram a maior parte do vapor d’água e os fenômenos meteorológicos do cotidiano. A estratosfera fica acima dela e possui características distintas, incluindo a maior concentração de ozônio atmosférico.",terms:["troposfera","estratosfera","tempo meteorológico"]}
  ]},
  {id:"fatores",title:"Fatores Climáticos",sub:"Por que lugares diferentes recebem e distribuem energia de modos diferentes",html:`
    ${svgRadiationAndFactors()}
    <p>Agora fazemos a pergunta mais importante: <strong>por que dois lugares da Terra podem ter climas diferentes?</strong> Os fatores climáticos alteram a maneira como a energia é recebida, armazenada ou redistribuída.</p>
    <h4>Latitude</h4><p>Quanto maior a latitude, em geral mais inclinada é a incidência média da radiação solar. A mesma energia tende a se distribuir por uma área maior, reduzindo a energia recebida por unidade de área.</p>
    <h4>Altitude</h4><p>Com o aumento da altitude, a pressão atmosférica diminui. Em condições usuais da troposfera, a temperatura também tende a cair com a altitude.</p>
    <h4>Maritimidade e continentalidade</h4><p>A água tem grande capacidade de armazenar calor. Como o oceano responde mais lentamente ao aquecimento e ao resfriamento, regiões próximas ao mar tendem a ter variações térmicas menores que áreas continentais comparáveis.</p>
    <h4>Albedo</h4><p>É a capacidade de uma superfície refletir radiação. Superfícies mais claras costumam refletir mais; superfícies escuras tendem a absorver mais energia. Isso interfere no balanço de energia.</p>
    <h4>Correntes marítimas</h4><p>Correntes deslocam grandes quantidades de calor e podem alterar temperatura e umidade das áreas costeiras. Correntes frias ajudam a explicar a aridez de algumas costas subtropicais, enquanto correntes quentes podem favorecer maior disponibilidade de umidade.</p>
    <div class="connection-box"><div class="k">Pense em mecanismo, não em lista</div><p>Latitude altera a <strong>entrada de energia</strong>; altitude altera <strong>pressão e temperatura</strong>; o mar altera o <strong>ritmo do aquecimento e do resfriamento</strong>; correntes redistribuem <strong>calor</strong>; albedo altera a <strong>reflexão</strong>. O clima resulta da interação.</p></div>
  `,quiz:[
   {type:"mc",q:"Por que a proximidade do oceano tende a reduzir a amplitude térmica?",options:["Porque a água troca energia de forma muito rápida","Porque a água armazena e libera energia lentamente, amortecendo variações de temperatura","Porque o litoral recebe sempre menos radiação solar","Porque o oceano impede a circulação do ar"],correct:1,explain:"A grande capacidade térmica da água faz do oceano um reservatório que suaviza variações térmicas."},
   {type:"mc",q:"Uma superfície clara e refletora altera principalmente qual propriedade do sistema de energia?",options:["Albedo","Umidade relativa","Pressão de vapor","Efeito de Coriolis"],correct:0,explain:"Albedo é a fração da radiação incidente refletida por uma superfície."},
   {type:"mc",q:"Um deserto costeiro pode ser muito seco mesmo estando próximo do oceano. Qual combinação ajuda a explicar esse caso?",options:["Corrente fria e condições atmosféricas que reduzem a convecção e a formação de chuva","Maritimidade elimina toda umidade","Latitude não tem qualquer relação com energia solar","Albedo alto produz chuva diretamente"],correct:0,explain:"Correntes frias podem resfriar a camada próxima à superfície e inibir convecção, contribuindo para condições áridas em conjunto com a circulação regional."},
   {type:"open",q:"Compare latitude, albedo e maritimidade: como cada um pode alterar a temperatura por mecanismos diferentes?",model:"Latitude altera o ângulo médio de incidência solar e a energia recebida por área. Albedo altera quanto da radiação incidente é refletida. Maritimidade modifica a resposta térmica pela presença de grande massa de água, que armazena e libera energia lentamente.",terms:["latitude","albedo","maritimidade"]},
   {type:"mc",challenge:true,q:"Duas áreas recebem radiação solar média semelhante. A primeira tem superfície escura e continental; a segunda, superfície clara e influência marítima. Qual diferença é mais plausível?",options:["A segunda tende a refletir mais energia e amortecer melhor a variação térmica","A primeira necessariamente terá mais chuva","A segunda sempre terá temperatura média menor em qualquer estação","As propriedades da superfície não afetam o balanço de energia"],correct:0,explain:"Superfícies com maior albedo refletem mais radiação, enquanto a influência marítima tende a reduzir a amplitude térmica."}
  ]},
  {id:"dinamica",title:"Dinâmica Climática",sub:"Conecte pressão, circulação, células e frentes",html:`
    <div class="idea-box"><div class="k">Pergunta-guia</div><p>Se o clima é um sistema em movimento, <strong>como o ar se desloca e organiza?</strong> A chave está nas diferenças de pressão e na circulação em várias escalas.</p></div>
    <h4>Ciclone e anticiclone</h4><div class="compare-grid"><div class="compare good"><div class="head">Ciclone</div><div class="line">baixa pressão relativa, convergência de ar na superfície, movimento ascendente e maior chance de nuvens e precipitação.</div></div><div class="compare"><div class="head">Anticiclone</div><div class="line">alta pressão relativa, ar descendente e circulação que tende a favorecer condições mais estáveis e secas.</div></div></div>
    <p>A palavra “ciclone” não significa automaticamente “furacão”. Ciclone pode ser usado para sistemas de baixa pressão em diferentes contextos; <strong>ciclone tropical</strong> é um tipo específico.</p>
    <h4>Circulação geral</h4>${svgCirculation()}<p>O aquecimento desigual da superfície ajuda a criar movimentos verticais e horizontais. Em escala planetária, esse processo participa da organização das células de Hadley, Ferrel e Polar.</p>
    <h4>ZCIT</h4><p>A Zona de Convergência Intertropical é uma faixa onde os ventos alísios dos dois hemisférios convergem. O ar quente e úmido tende a subir nessa região, favorecendo convecção e chuva.</p>
    <h4>Frentes</h4>${svgFronts()}<p>Frentes são zonas de transição entre massas de ar. Uma frente fria ocorre quando o ar frio avança e desloca o ar quente; uma frente quente ocorre quando o ar quente avança sobre o ar frio. A forma como o ar sobe ajuda a explicar diferenças na nebulosidade e na precipitação.</p>
    <div class="why-box"><div class="k">Conexão forte</div><p><strong>diferença de aquecimento → diferença de pressão → movimento do ar → convergência/divergência → subida/descida → nuvens e chuva.</strong> Essa cadeia aparece novamente no El Niño e nos ciclones tropicais.</p></div>
  `,quiz:[
   {type:"mc",q:"Em um sistema de baixa pressão, qual processo favorece a formação de nuvens e chuva?",options:["Subsidência persistente e aquecimento por compressão","Convergência próxima à superfície e movimento ascendente do ar","Ausência completa de vapor d’água","Aumento da estabilidade pela descida do ar"],correct:1,explain:"A convergência pode forçar ascensão; ao subir, o ar se expande, esfria e pode atingir saturação."},
   {type:"mc",q:"Por que a ZCIT costuma ser associada a forte nebulosidade e precipitação?",options:["Porque é uma faixa de alta pressão seca","Porque a convergência dos alísios favorece a subida de ar quente e úmido","Porque o ar sempre desce sobre o Equador","Porque o oceano deixa de evaporar nessa faixa"],correct:1,explain:"A convergência dos alísios favorece movimento ascendente e convecção, criando condições para nuvens e chuva."},
   {type:"mc",q:"O que caracteriza uma frente fria?",options:["O ar quente avança sobre uma massa de ar mais fria sem deslocá-la","Uma massa de ar frio avança e força o ar mais quente a subir","Uma área de alta pressão permanece parada sobre o oceano","Um ciclone tropical atravessa uma montanha"],correct:1,explain:"Na frente fria, o ar frio avança e promove a ascensão do ar quente, podendo gerar nebulosidade e precipitação."},
   {type:"open",q:"Construa uma cadeia causal ligando diferença de pressão, vento, movimento vertical do ar e chuva.",model:"Diferenças de pressão ajudam a gerar movimento do ar. A convergência pode forçar ascensão; ao subir, o ar esfria e pode atingir saturação, favorecendo condensação, nuvens e precipitação.",terms:["pressão","vento","ascensão","condensação"]},
   {type:"mc",challenge:true,q:"Qual situação favorece mais a instabilidade atmosférica?",options:["Ar quente e úmido próximo à superfície com condições que favorecem sua ascensão","Ar seco descendente em um sistema estável","Ausência de gradientes de pressão e de movimento vertical","Subsidência intensa sobre toda a região"],correct:0,explain:"Ar quente e úmido próximo à superfície pode liberar energia e favorecer convecção quando o ambiente permite ascensão."}
  ]},
  {id:"elnino",title:"El Niño e La Niña",sub:"Veja o clima como um sistema oceano-atmosfera acoplado",html:`
    ${svgENSO()}
    <p>El Niño e La Niña são fases do <strong>ENSO</strong> (El Niño–Oscilação Sul), um fenômeno de grande escala que conecta o estado do oceano tropical do Pacífico com mudanças na circulação atmosférica.</p>
    <h4>Condições próximas do normal</h4><p>Os ventos alísios normalmente empurram águas superficiais mais quentes para oeste. Perto da costa oeste da América do Sul, o processo de ressurgência ajuda a trazer águas mais frias e ricas em nutrientes para a superfície.</p>
    <h4>El Niño</h4><p>Durante El Niño, as águas superficiais do Pacífico equatorial central e leste ficam anormalmente quentes. Isso altera os ventos, a distribuição da convecção e os padrões de chuva.</p>
    <h4>La Niña</h4><p>La Niña é a fase fria: o Pacífico equatorial central e leste fica anormalmente mais frio, enquanto a circulação de ventos e a ressurgência se fortalecem.</p>
    <div class="callout-quote">O ponto central não é “El Niño = quente”. É: <strong>mudou a temperatura do oceano → mudou a atmosfera → mudaram circulação, chuva e temperatura em regiões distantes.</strong></div>
    <div class="connection-box"><div class="k">Brasil: cuidado com respostas automáticas</div><p>Existem padrões típicos para várias regiões do Brasil, mas eles são <strong>tendências</strong>, não uma regra mecânica para cada cidade e cada episódio. A resposta local depende da época do ano, da região e da interação com outros sistemas atmosféricos.</p></div>
  `,quiz:[
   {type:"mc",q:"O que caracteriza o El Niño no Pacífico equatorial?",options:["Resfriamento anômalo persistente das águas centrais e orientais","Aquecimento anômalo das águas do Pacífico equatorial central e leste, acompanhado de mudanças atmosféricas","Aumento uniforme da temperatura de todos os oceanos","Apenas uma mudança de temperatura no Atlântico"],correct:1,explain:"El Niño é uma fase do ENSO marcada por aquecimento anômalo no Pacífico equatorial central e leste e mudanças acopladas na atmosfera."},
   {type:"mc",q:"Por que uma anomalia no Pacífico pode afetar chuva em regiões distantes?",options:["Porque a água percorre fisicamente o planeta em poucos dias","Porque alterações no acoplamento oceano-atmosfera reorganizam convecção, ventos e circulação em grande escala","Porque toda chuva mundial nasce no Pacífico","Porque o relevo deixa de influenciar o clima"],correct:1,explain:"O ENSO altera padrões de circulação atmosférica e distribuição de convecção, produzindo teleconexões climáticas."},
   {type:"mc",q:"Qual relação entre El Niño e La Niña está correta?",options:["São nomes para o mesmo estado do Pacífico","São fases opostas de um sistema de variabilidade oceano-atmosférica chamado ENSO","Uma ocorre apenas no inverno e a outra apenas no verão","Uma pertence ao Atlântico e outra ao Pacífico"],correct:1,explain:"El Niño e La Niña são fases quentes e frias, respectivamente, de um fenômeno acoplado do Pacífico."},
   {type:"open",q:"Explique por que os efeitos do El Niño no Brasil não são iguais em todas as regiões.",model:"As respostas dependem da circulação atmosférica, da posição e intensidade das anomalias no Pacífico e das condições regionais, como relevo e disponibilidade de umidade. Por isso, o sinal de chuva e temperatura pode variar entre regiões.",terms:["teleconexão","circulação","variabilidade regional"]},
   {type:"mc",challenge:true,q:"Imagine que o Pacífico equatorial apresenta uma anomalia quente. Qual evidência reforçaria a interpretação de um episódio de ENSO em vez de uma oscilação local isolada?",options:["Somente uma medição costeira","Mudanças coerentes de temperatura oceânica junto com respostas atmosféricas características e persistência espacial e temporal","Apenas um dia de chuva em uma cidade","Uma mudança de temperatura no Atlântico sem relação atmosférica"],correct:1,explain:"O ENSO é um fenômeno acoplado: a interpretação depende da relação entre anomalias oceânicas e atmosféricas e de sua persistência."}
  ]},
  {id:"ciclones",title:"Ciclones Tropicais",sub:"Entenda a retroalimentação entre oceano quente e atmosfera",html:`
    ${svgTropicalCyclone()}
    <p>Um <strong>ciclone tropical</strong> é um sistema organizado de baixa pressão que se desenvolve em ambiente tropical e utiliza energia do oceano quente. “Furacão” e “tufão” são nomes regionais usados para ciclones tropicais que atingem determinada intensidade em diferentes bacias.</p>
    <h4>O mecanismo</h4><p>Água quente fornece energia por evaporação. O vapor sobe, condensa e libera calor latente. Esse aquecimento sustenta convecção, ajuda a aprofundar a circulação e reforça a organização do sistema.</p>
    <p>A temperatura do oceano é importante, mas <strong>não é suficiente sozinha</strong>. Um ambiente favorável também envolve umidade, pouca variação vertical dos ventos, uma perturbação inicial e distância suficiente do Equador para que o efeito de Coriolis contribua para a organização da circulação. Uma referência comum é água do mar em torno de <strong>26,5 °C ou mais</strong>, em profundidade suficiente.</p>
    <h4>Tornado e ciclone tropical não são a mesma coisa</h4><div class="compare-grid"><div class="compare"><div class="head">Ciclone tropical</div><div class="line">sistema de grande escala, alimentado principalmente pelo calor do oceano, com duração que pode se estender por vários dias.</div></div><div class="compare"><div class="head">Tornado</div><div class="line">coluna de ar em rotação muito menor e de duração geralmente muito mais curta, associada a tempestades severas.</div></div></div>
    <div class="warning-box"><div class="k">Erro comum</div><p>“Água a 26 °C = vai formar furacão” está errado. Temperatura do mar é uma condição importante, não um gatilho único.</p></div>
  `,quiz:[
   {type:"mc",q:"Qual cadeia representa melhor uma parte importante da intensificação de um ciclone tropical?",options:["Água quente → evaporação → ascensão/condensação → liberação de calor → manutenção da convecção","Água fria → menor evaporação → fortalecimento automático","Solo seco → ausência de vapor → intensificação","Alta pressão → subsidência → convecção crescente"],correct:0,explain:"O oceano quente favorece evaporação; a condensação do vapor libera calor latente que ajuda a sustentar a convecção e a circulação."},
   {type:"mc",q:"Por que água do mar próxima de 26,5 °C não garante a formação de um ciclone tropical?",options:["Porque a temperatura oceânica não participa do processo","Porque são necessárias também condições atmosféricas, perturbação inicial e ambiente favorável à organização da circulação","Porque ciclones só se formam sobre terra","Porque o vapor d’água reduz a convecção"],correct:1,explain:"Temperatura do oceano é uma condição importante, mas não suficiente. Umidade, cisalhamento, perturbação e Coriolis também importam."},
   {type:"mc",q:"Por que um ciclone tropical tende a não se organizar exatamente sobre o Equador?",options:["Porque não há oceanos no Equador","Porque o efeito de Coriolis é muito fraco perto do Equador para organizar a rotação do sistema","Porque o ar não pode subir no Equador","Porque a temperatura do oceano é sempre baixa no Equador"],correct:1,explain:"A rotação da Terra contribui para organizar a circulação ciclônica, mas o parâmetro de Coriolis é muito pequeno próximo ao Equador."},
   {type:"open",q:"Diferencie ciclone tropical e tornado usando escala, duração e fonte de energia, sem reduzir a resposta ao tamanho.",model:"Ciclones tropicais são sistemas de grande escala, que podem durar vários dias e obtêm energia principalmente do oceano quente e da convecção organizada. Tornados são fenômenos muito menores e geralmente curtos, ligados a tempestades severas e a uma dinâmica distinta.",terms:["escala","duração","energia"]},
   {type:"mc",challenge:true,q:"Dois sistemas estão sobre oceanos igualmente quentes. Um possui forte cisalhamento vertical dos ventos; o outro, cisalhamento fraco. Qual tem ambiente mais favorável à organização de um ciclone tropical?",options:["O de forte cisalhamento, porque mistura melhor toda a atmosfera","O de cisalhamento fraco, porque a circulação pode permanecer mais organizada verticalmente","Os dois são equivalentes porque só a temperatura do mar importa","Nenhum, porque ciclones não dependem da atmosfera"],correct:1,explain:"Cisalhamento vertical forte pode desorganizar a convecção e a circulação; ambiente com cisalhamento fraco é mais favorável."}
  ]},
  {id:"mudancas",title:"Mudanças Climáticas",sub:"Conecte balanço de energia, ação humana e riscos",html:`
    ${svgGreenhouse()}${svgClimateChangeChain()}
    <p>O efeito estufa natural faz parte do funcionamento térmico do planeta. O problema atual é o <strong>aumento da concentração de gases de efeito estufa devido principalmente a atividades humanas</strong>, alterando o balanço de energia da Terra.</p>
    <h4>De onde vem o aumento?</h4><ul><li>queima de carvão, petróleo e gás;</li><li>mudanças no uso da terra e desmatamento;</li><li>agropecuária e outras fontes de metano e óxido nitroso;</li><li>processos industriais e manejo de resíduos.</li></ul>
    <h4>O que muda?</h4><p>O aquecimento do sistema climático altera médias e distribuições de temperatura, disponibilidade de água, gelo, nível do mar e o risco de alguns extremos. O efeito não é idêntico em todos os lugares: vulnerabilidade e impactos dependem da região e das características sociais e ambientais.</p>
    <h4>Por que eventos extremos precisam de contexto?</h4><p>Um evento específico resulta da combinação de circulação atmosférica, oceano, relevo, uso da terra e outras condições. A mudança climática pode alterar o pano de fundo que influencia frequência ou intensidade de alguns extremos, mas não significa que cada evento extremo tenha uma causa única.</p>
    <h4>Política climática</h4><p>O <strong>Protocolo de Kyoto</strong> estabeleceu metas de redução para países desenvolvidos dentro de um sistema internacional específico. O <strong>Acordo de Paris</strong> de 2015 organizou compromissos nacionais chamados NDCs e estabeleceu o objetivo de manter o aquecimento global bem abaixo de 2 °C e perseguir esforços para limitá-lo a 1,5 °C.</p>
    <div class="why-box"><div class="k">Conexão com tudo que veio antes</div><p>Latitude, altitude, circulação, oceano, umidade, correntes e balanço de energia continuam presentes. A diferença é que agora estamos alterando <strong>forçantes do sistema climático</strong>, especialmente a composição atmosférica.</p></div>
  `,quiz:[
   {type:"mc",q:"Qual cadeia explica melhor o aquecimento global antropogênico?",options:["Atividades humanas → aumento de gases de efeito estufa → alteração do balanço de energia → aquecimento do sistema","Mais chuva → menos CO₂ → aquecimento direto","Mais vento → menos vapor → aquecimento","Menos radiação recebida → maior retenção de energia"],correct:0,explain:"O aumento antropogênico de gases de efeito estufa altera o balanço energético do sistema climático e produz aquecimento."},
   {type:"mc",q:"Por que o efeito estufa natural não deve ser tratado como sinônimo de mudança climática antropogênica?",options:["Porque o efeito estufa natural não existe","Porque o efeito estufa natural faz parte do equilíbrio térmico da Terra; a atividade humana intensifica a concentração de gases de efeito estufa","Porque CO₂ não interage com radiação infravermelha","Porque o clima não possui balanço energético"],correct:1,explain:"O efeito estufa natural é necessário. A questão atual é a intensificação do efeito associada ao aumento antropogênico de gases de efeito estufa."},
   {type:"mc",q:"Por que um evento extremo isolado não deve ser atribuído automaticamente à mudança climática?",options:["Porque o clima não influencia eventos extremos","Porque cada evento resulta de condições locais e circulação, enquanto a mudança climática altera probabilidades e contextos de risco","Porque eventos extremos não podem ser observados","Porque apenas a temperatura média importa"],correct:1,explain:"A atribuição de extremos considera o contexto físico e estatístico; mudança climática pode alterar a probabilidade ou intensidade de alguns eventos sem ser uma causa única automática."},
   {type:"open",q:"Conecte atividade humana, gases de efeito estufa, balanço de energia e aquecimento em uma única explicação causal.",model:"Atividades humanas aumentam a concentração de gases de efeito estufa na atmosfera. Esses gases absorvem e reemitem parte da radiação infravermelha, alterando o balanço de energia do sistema e contribuindo para o aquecimento global.",terms:["GEE","balanço de energia","aquecimento"]},
   {type:"mc",challenge:true,q:"Uma região aquece, mas o efeito sobre chuva e extremos não é igual ao de outra região. Qual explicação é mais coerente?",options:["Todos os lugares respondem de maneira idêntica a uma mudança global","A resposta regional depende da circulação, oceano, relevo, disponibilidade de água e vulnerabilidades locais","A latitude deixa de existir quando o planeta aquece","Mudança climática afeta apenas a temperatura do ar"],correct:1,explain:"O aquecimento global atua sobre um sistema climático heterogêneo; processos físicos e condições locais modulam os impactos regionais."}
  ]}
 ],
 questions:[
  
   {type:"mc",title:"Tempo e clima",q:"Uma estação registra 34 °C e chuva intensa em uma tarde. Qual conclusão é mais defensável?",options:["O clima da cidade é definido por essa tarde","Isso descreve o tempo; para caracterizar o clima é preciso analisar séries e padrões","A chuva prova uma mudança climática","A temperatura deixa de ser uma variável climática"],correct:1,explain:"A observação é pontual. Clima é caracterizado por padrões e variabilidade em escalas de tempo longas."},
  
   {type:"mc",challenge:true,q:"Uma cidade teve três anos seguidos acima da média histórica. Qual análise seria mais adequada antes de afirmar uma mudança permanente?",options:["Comparar os dados apenas com o último ano","Examinar uma série mais longa, a variabilidade e outros indicadores climáticos","Descartar os anos porque extremos não contam","Usar somente a maior temperatura registrada"],correct:1,explain:"Períodos curtos podem conter variabilidade natural. A avaliação climática precisa de contexto temporal e estatístico."},
  
   {type:"open",q:"Explique, em poucas frases, por que previsão do tempo e climatologia respondem perguntas diferentes.",model:"A previsão do tempo busca estimar o estado atmosférico em uma escala curta. A climatologia analisa padrões, médias, variabilidade e extremos ao longo de períodos longos.",terms:["tempo","clima","escala temporal"]},
  
   {type:"mc",q:"Duas cidades têm a mesma temperatura média anual, mas uma possui verões e invernos muito mais contrastantes. Qual medida ajuda diretamente a perceber essa diferença?",options:["Amplitude térmica","Pressão atmosférica média","Latitude absoluta","Precipitação anual isolada"],correct:0,explain:"A amplitude térmica evidencia a diferença entre valores de temperatura em um período e pode revelar contrastes que a média esconde."},
  
   {type:"mc",q:"Depois que ar úmido sobe ao encontrar uma serra, ocorre resfriamento e formação de nuvens. Que mecanismo de precipitação está mais diretamente envolvido?",options:["Convectivo","Orográfico","Frontal","Ciclônico exclusivamente"],correct:1,explain:"Na chuva orográfica, o relevo força a ascensão do ar, favorecendo resfriamento, condensação e precipitação."},
  
   {type:"open",q:"Compare chuva frontal, orográfica e convectiva pelo processo que força o ar a subir.",model:"Na frontal, a ascensão ocorre pela interação entre massas de ar de características diferentes. Na orográfica, o relevo força a subida. Na convectiva, o aquecimento da superfície gera ar mais quente e ascendente.",terms:["frontal","orográfica","convectiva"]},
  
   {type:"mc",q:"Em qual camada ocorrem a maior parte das nuvens, chuvas e outros fenômenos meteorológicos próximos à superfície?",options:["Estratosfera","Troposfera","Mesosfera","Exosfera"],correct:1,explain:"A troposfera é a camada inferior e concentra a maior parte da massa atmosférica e do vapor d’água relevante ao tempo meteorológico."},
  
   {type:"mc",q:"Qual sequência apresenta as camadas principais da atmosfera a partir da superfície?",options:["Troposfera, estratosfera, mesosfera, termosfera, exosfera","Estratosfera, troposfera, termosfera, mesosfera, exosfera","Troposfera, mesosfera, estratosfera, exosfera, termosfera","Exosfera, termosfera, mesosfera, estratosfera, troposfera"],correct:0,explain:"A ordem convencional é troposfera, estratosfera, mesosfera, termosfera e exosfera."},
  
   {type:"mc",challenge:true,q:"Por que conhecer a estrutura vertical da atmosfera ajuda na climatologia?",options:["Porque todas as camadas têm exatamente o mesmo comportamento","Porque permite relacionar processos e propriedades à altitude em vez de tratar a atmosfera como uma camada uniforme","Porque apenas a exosfera influencia o clima","Porque a altitude não altera os processos atmosféricos"],correct:1,explain:"Temperatura, composição e processos variam com a altitude; distinguir as camadas evita generalizações incorretas."},
  
   {type:"mc",q:"Por que a proximidade do oceano tende a reduzir a amplitude térmica?",options:["Porque a água troca energia de forma muito rápida","Porque a água armazena e libera energia lentamente, amortecendo variações de temperatura","Porque o litoral recebe sempre menos radiação solar","Porque o oceano impede a circulação do ar"],correct:1,explain:"A grande capacidade térmica da água faz do oceano um reservatório que suaviza variações térmicas."},
  
   {type:"mc",q:"Um deserto costeiro pode ser muito seco mesmo estando próximo do oceano. Qual combinação ajuda a explicar esse caso?",options:["Corrente fria e condições atmosféricas que reduzem a convecção e a formação de chuva","Maritimidade elimina toda umidade","Latitude não tem qualquer relação com energia solar","Albedo alto produz chuva diretamente"],correct:0,explain:"Correntes frias podem resfriar a camada próxima à superfície e inibir convecção, contribuindo para condições áridas em conjunto com a circulação regional."},
  
   {type:"open",q:"Compare latitude, albedo e maritimidade: como cada um pode alterar a temperatura por mecanismos diferentes?",model:"Latitude altera o ângulo médio de incidência solar e a energia recebida por área. Albedo altera quanto da radiação incidente é refletida. Maritimidade modifica a resposta térmica pela presença de grande massa de água, que armazena e libera energia lentamente.",terms:["latitude","albedo","maritimidade"]},
  
   {type:"mc",q:"Em um sistema de baixa pressão, qual processo favorece a formação de nuvens e chuva?",options:["Subsidência persistente e aquecimento por compressão","Convergência próxima à superfície e movimento ascendente do ar","Ausência completa de vapor d’água","Aumento da estabilidade pela descida do ar"],correct:1,explain:"A convergência pode forçar ascensão; ao subir, o ar se expande, esfria e pode atingir saturação."},
  
   {type:"mc",q:"O que caracteriza uma frente fria?",options:["O ar quente avança sobre uma massa de ar mais fria sem deslocá-la","Uma massa de ar frio avança e força o ar mais quente a subir","Uma área de alta pressão permanece parada sobre o oceano","Um ciclone tropical atravessa uma montanha"],correct:1,explain:"Na frente fria, o ar frio avança e promove a ascensão do ar quente, podendo gerar nebulosidade e precipitação."},
  
   {type:"open",q:"Construa uma cadeia causal ligando diferença de pressão, vento, movimento vertical do ar e chuva.",model:"Diferenças de pressão ajudam a gerar movimento do ar. A convergência pode forçar ascensão; ao subir, o ar esfria e pode atingir saturação, favorecendo condensação, nuvens e precipitação.",terms:["pressão","vento","ascensão","condensação"]},
  
   {type:"mc",q:"O que caracteriza o El Niño no Pacífico equatorial?",options:["Resfriamento anômalo persistente das águas centrais e orientais","Aquecimento anômalo das águas do Pacífico equatorial central e leste, acompanhado de mudanças atmosféricas","Aumento uniforme da temperatura de todos os oceanos","Apenas uma mudança de temperatura no Atlântico"],correct:1,explain:"El Niño é uma fase do ENSO marcada por aquecimento anômalo no Pacífico equatorial central e leste e mudanças acopladas na atmosfera."},
  
   {type:"mc",q:"Qual relação entre El Niño e La Niña está correta?",options:["São nomes para o mesmo estado do Pacífico","São fases opostas de um sistema de variabilidade oceano-atmosférica chamado ENSO","Uma ocorre apenas no inverno e a outra apenas no verão","Uma pertence ao Atlântico e outra ao Pacífico"],correct:1,explain:"El Niño e La Niña são fases quentes e frias, respectivamente, de um fenômeno acoplado do Pacífico."},
  
   {type:"open",q:"Explique por que os efeitos do El Niño no Brasil não são iguais em todas as regiões.",model:"As respostas dependem da circulação atmosférica, da posição e intensidade das anomalias no Pacífico e das condições regionais, como relevo e disponibilidade de umidade. Por isso, o sinal de chuva e temperatura pode variar entre regiões.",terms:["teleconexão","circulação","variabilidade regional"]},
  
   {type:"mc",q:"Qual cadeia representa melhor uma parte importante da intensificação de um ciclone tropical?",options:["Água quente → evaporação → ascensão/condensação → liberação de calor → manutenção da convecção","Água fria → menor evaporação → fortalecimento automático","Solo seco → ausência de vapor → intensificação","Alta pressão → subsidência → convecção crescente"],correct:0,explain:"O oceano quente favorece evaporação; a condensação do vapor libera calor latente que ajuda a sustentar a convecção e a circulação."},
  
   {type:"mc",q:"Por que um ciclone tropical tende a não se organizar exatamente sobre o Equador?",options:["Porque não há oceanos no Equador","Porque o efeito de Coriolis é muito fraco perto do Equador para organizar a rotação do sistema","Porque o ar não pode subir no Equador","Porque a temperatura do oceano é sempre baixa no Equador"],correct:1,explain:"A rotação da Terra contribui para organizar a circulação ciclônica, mas o parâmetro de Coriolis é muito pequeno próximo ao Equador."},
  
   {type:"open",q:"Diferencie ciclone tropical e tornado usando escala, duração e fonte de energia, sem reduzir a resposta ao tamanho.",model:"Ciclones tropicais são sistemas de grande escala, que podem durar vários dias e obtêm energia principalmente do oceano quente e da convecção organizada. Tornados são fenômenos muito menores e geralmente curtos, ligados a tempestades severas e a uma dinâmica distinta.",terms:["escala","duração","energia"]},
  
   {type:"mc",q:"Qual cadeia explica melhor o aquecimento global antropogênico?",options:["Atividades humanas → aumento de gases de efeito estufa → alteração do balanço de energia → aquecimento do sistema","Mais chuva → menos CO₂ → aquecimento direto","Mais vento → menos vapor → aquecimento","Menos radiação recebida → maior retenção de energia"],correct:0,explain:"O aumento antropogênico de gases de efeito estufa altera o balanço energético do sistema climático e produz aquecimento."},
  
   {type:"mc",q:"Por que um evento extremo isolado não deve ser atribuído automaticamente à mudança climática?",options:["Porque o clima não influencia eventos extremos","Porque cada evento resulta de condições locais e circulação, enquanto a mudança climática altera probabilidades e contextos de risco","Porque eventos extremos não podem ser observados","Porque apenas a temperatura média importa"],correct:1,explain:"A atribuição de extremos considera o contexto físico e estatístico; mudança climática pode alterar a probabilidade ou intensidade de alguns eventos sem ser uma causa única automática."},
  
   {type:"open",q:"Conecte atividade humana, gases de efeito estufa, balanço de energia e aquecimento em uma única explicação causal.",model:"Atividades humanas aumentam a concentração de gases de efeito estufa na atmosfera. Esses gases absorvem e reemitem parte da radiação infravermelha, alterando o balanço de energia do sistema e contribuindo para o aquecimento global.",terms:["GEE","balanço de energia","aquecimento"]}
 ],
 flashcards:[
  {id:"fc0",diff:"facil",front:"Qual diferença essencial existe entre tempo e clima?",back:"Tempo é o estado momentâneo da atmosfera; clima é a descrição estatística dos padrões e da variabilidade desse tempo em longo prazo."},
  {id:"fc1",diff:"medio",front:"Por que a média anual não basta para comparar dois climas?",back:"Porque médias semelhantes podem esconder amplitudes térmicas, sazonalidades e frequências de extremos diferentes."},
  {id:"fc2",diff:"medio",front:"O que distingue chuva orográfica de chuva convectiva?",back:"Na orográfica, o relevo força a subida do ar. Na convectiva, o aquecimento da superfície favorece a subida do ar quente."},
  {id:"fc3",diff:"medio",front:"Como diferenças de pressão ajudam a gerar vento?",back:"Elas produzem um gradiente de pressão que impulsiona o movimento do ar; a rotação da Terra e o relevo alteram a trajetória real."},
  {id:"fc4",diff:"dificil",front:"Quais são as cinco camadas principais da atmosfera?",back:"Troposfera, estratosfera, mesosfera, termosfera e exosfera."},
  {id:"fc5",diff:"medio",front:"Por que o ozônio é associado à estratosfera?",back:"Porque a maior parte do ozônio atmosférico está concentrada na estratosfera, onde absorve parte da radiação ultravioleta."},
  {id:"fc6",diff:"dificil",front:"Por que a maritimidade tende a reduzir a amplitude térmica?",back:"A água armazena e libera calor lentamente, amortecendo variações de temperatura em comparação com superfícies continentais."},
  {id:"fc7",diff:"dificil",front:"Como o ENSO conecta oceano e atmosfera?",back:"Anomalias de temperatura no Pacífico alteram ventos, convecção e pressão, reorganizando padrões de circulação e precipitação."},
  {id:"fc8",diff:"dificil",front:"Por que água quente sozinha não cria um ciclone tropical?",back:"Porque também são necessários ambiente atmosférico adequado, umidade, pouca variação vertical dos ventos, perturbação inicial e efeito de Coriolis."},
  {id:"fc9",diff:"dificil",front:"Qual é a diferença entre efeito estufa natural e intensificação antrópica?",back:"O efeito estufa natural ajuda a manter o planeta habitável; o aumento antropogênico dos gases de efeito estufa reforça a retenção de energia e aquece o sistema."}
 ],
 keywords:[
  {id:"kw0",term:"Amplitude térmica",def:"Diferença entre dois valores de temperatura, como máxima e mínima em um período."},
  {id:"kw1",term:"Umidade relativa",def:"Razão percentual entre o vapor presente e a quantidade máxima que o ar pode conter naquela temperatura."},
  {id:"kw2",term:"Chuva orográfica",def:"Precipitação favorecida pela subida do ar ao encontrar uma barreira de relevo."},
  {id:"kw3",term:"Chuva convectiva",def:"Precipitação associada à subida de ar aquecido, com forte movimento convectivo."},
  {id:"kw4",term:"Maritimidade",def:"Influência do oceano que tende a amortecer variações de temperatura e modificar a umidade costeira."},
  {id:"kw5",term:"Continentalidade",def:"Influência reduzida do oceano; áreas interiores tendem a apresentar maior amplitude térmica."},
  {id:"kw6",term:"Troposfera",def:"Camada inferior da atmosfera, diretamente ligada ao tempo meteorológico."},
  {id:"kw7",term:"Estratosfera",def:"Camada acima da troposfera que concentra a maior parte do ozônio atmosférico."},
  {id:"kw8",term:"Albedo",def:"Fração da radiação incidente que uma superfície reflete."},
  {id:"kw9",term:"Efeito estufa",def:"Processo no qual gases atmosféricos absorvem e reemitem parte da radiação infravermelha terrestre."},
  {id:"kw10",term:"Corrente de Humboldt",def:"Corrente fria associada à costa oeste da América do Sul, influenciando temperatura, umidade e produtividade marinha."},
  {id:"kw11",term:"Ciclone",def:"Sistema de baixa pressão; não é sinônimo automático de ciclone tropical."},
  {id:"kw12",term:"Anticiclone",def:"Sistema de alta pressão, geralmente associado a subsidência e maior estabilidade do tempo."},
  {id:"kw13",term:"Célula de Hadley",def:"Circulação tropical de grande escala ligada ao aquecimento diferencial e ao transporte de energia entre baixas latitudes."},
  {id:"kw14",term:"ZCIT",def:"Faixa de convergência dos alísios perto do Equador, associada a forte convecção."},
  {id:"kw15",term:"ENSO",def:"Sistema oceano-atmosfera do Pacífico que inclui as fases El Niño e La Niña."},
  {id:"kw16",term:"El Niño",def:"Fase quente do ENSO, com águas anormalmente quentes no Pacífico equatorial central e leste."},
  {id:"kw17",term:"La Niña",def:"Fase fria do ENSO, com águas anormalmente frias no Pacífico equatorial central e leste."},
  {id:"kw18",term:"Ciclone tropical",def:"Sistema tropical de baixa pressão alimentado pelo calor do oceano e dependente de condições atmosféricas favoráveis."},
  {id:"kw19",term:"Gases de efeito estufa",def:"Gases que absorvem parte da radiação infravermelha emitida pela superfície e pela atmosfera."},
  {id:"kw20",term:"Acordo de Paris",def:"Acordo internacional de 2015 que organiza metas nacionais e busca manter o aquecimento bem abaixo de 2 °C, perseguindo 1,5 °C."}
 ]
}];

export { SUBJECTS };
